/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Odev1._481;

import java.util.ArrayList;

public class App {
    public static boolean search(ArrayList<Integer> array, int e) {
        System.out.println("inside search");
        if (array == null)
            return false;

        for (int elt : array) {
            if (elt == e)
                return true;
        }
        return false;
    }
}
